// flow-typed signature: 741d8a133b81ee4f0f29b0320c083f3c
// flow-typed version: <<STUB>>/base32.js_v^0.1.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base32.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base32.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'base32.js/base32' {
  declare module.exports: any;
}

declare module 'base32.js/dist/base32' {
  declare module.exports: any;
}

declare module 'base32.js/dist/base32.min' {
  declare module.exports: any;
}

declare module 'base32.js/karma.conf' {
  declare module.exports: any;
}

declare module 'base32.js/test/base32_test' {
  declare module.exports: any;
}

declare module 'base32.js/test/fixtures' {
  declare module.exports: any;
}

declare module 'base32.js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'base32.js/base32.js' {
  declare module.exports: $Exports<'base32.js/base32'>;
}
declare module 'base32.js/dist/base32.js' {
  declare module.exports: $Exports<'base32.js/dist/base32'>;
}
declare module 'base32.js/dist/base32.min.js' {
  declare module.exports: $Exports<'base32.js/dist/base32.min'>;
}
declare module 'base32.js/index' {
  declare module.exports: $Exports<'base32.js'>;
}
declare module 'base32.js/index.js' {
  declare module.exports: $Exports<'base32.js'>;
}
declare module 'base32.js/karma.conf.js' {
  declare module.exports: $Exports<'base32.js/karma.conf'>;
}
declare module 'base32.js/test/base32_test.js' {
  declare module.exports: $Exports<'base32.js/test/base32_test'>;
}
declare module 'base32.js/test/fixtures.js' {
  declare module.exports: $Exports<'base32.js/test/fixtures'>;
}
declare module 'base32.js/webpack.config.js' {
  declare module.exports: $Exports<'base32.js/webpack.config'>;
}
