// flow-typed signature: d863c5124805ce10b389216efda19813
// flow-typed version: <<STUB>>/sha.js_v^2.3.6/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sha.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sha.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sha.js/bin' {
  declare module.exports: any;
}

declare module 'sha.js/hash' {
  declare module.exports: any;
}

declare module 'sha.js/sha' {
  declare module.exports: any;
}

declare module 'sha.js/sha1' {
  declare module.exports: any;
}

declare module 'sha.js/sha224' {
  declare module.exports: any;
}

declare module 'sha.js/sha256' {
  declare module.exports: any;
}

declare module 'sha.js/sha384' {
  declare module.exports: any;
}

declare module 'sha.js/sha512' {
  declare module.exports: any;
}

declare module 'sha.js/test/hash' {
  declare module.exports: any;
}

declare module 'sha.js/test/test' {
  declare module.exports: any;
}

declare module 'sha.js/test/vectors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sha.js/bin.js' {
  declare module.exports: $Exports<'sha.js/bin'>;
}
declare module 'sha.js/hash.js' {
  declare module.exports: $Exports<'sha.js/hash'>;
}
declare module 'sha.js/index' {
  declare module.exports: $Exports<'sha.js'>;
}
declare module 'sha.js/index.js' {
  declare module.exports: $Exports<'sha.js'>;
}
declare module 'sha.js/sha.js' {
  declare module.exports: $Exports<'sha.js/sha'>;
}
declare module 'sha.js/sha1.js' {
  declare module.exports: $Exports<'sha.js/sha1'>;
}
declare module 'sha.js/sha224.js' {
  declare module.exports: $Exports<'sha.js/sha224'>;
}
declare module 'sha.js/sha256.js' {
  declare module.exports: $Exports<'sha.js/sha256'>;
}
declare module 'sha.js/sha384.js' {
  declare module.exports: $Exports<'sha.js/sha384'>;
}
declare module 'sha.js/sha512.js' {
  declare module.exports: $Exports<'sha.js/sha512'>;
}
declare module 'sha.js/test/hash.js' {
  declare module.exports: $Exports<'sha.js/test/hash'>;
}
declare module 'sha.js/test/test.js' {
  declare module.exports: $Exports<'sha.js/test/test'>;
}
declare module 'sha.js/test/vectors.js' {
  declare module.exports: $Exports<'sha.js/test/vectors'>;
}
