// flow-typed signature: d33742275dc0c1435f98c0f2d31f0764
// flow-typed version: <<STUB>>/@ledgerhq/hw-app-str_v^4.57.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-app-str'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-app-str' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-app-str/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-str/flow-typed/npm/base32.js_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-str/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-str/flow-typed/npm/sha.js_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-str/flow-typed/npm/tweetnacl_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-str/src/Str' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-str/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-app-str/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-str/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-str/flow-typed/npm/base32.js_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-str/flow-typed/npm/base32.js_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-str/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-str/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-app-str/flow-typed/npm/sha.js_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-str/flow-typed/npm/sha.js_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-str/flow-typed/npm/tweetnacl_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-str/flow-typed/npm/tweetnacl_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-str/src/Str.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-str/src/Str'>;
}
declare module '@ledgerhq/hw-app-str/src/utils.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-str/src/utils'>;
}
