// flow-typed signature: 41aba2f7c2040f448ad8e65b92bc1fd4
// flow-typed version: <<STUB>>/@ledgerhq/hw-app-eth_v^4.57.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-app-eth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-app-eth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-app-eth/data/erc20' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/erc20' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/flow-typed/npm/@ledgerhq/errors_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/src/erc20' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/src/Eth' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-app-eth/data/erc20.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/data/erc20'>;
}
declare module '@ledgerhq/hw-app-eth/erc20.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/erc20'>;
}
declare module '@ledgerhq/hw-app-eth/flow-typed/npm/@ledgerhq/errors_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/flow-typed/npm/@ledgerhq/errors_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-eth/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-eth/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-app-eth/src/erc20.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/src/erc20'>;
}
declare module '@ledgerhq/hw-app-eth/src/Eth.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/src/Eth'>;
}
declare module '@ledgerhq/hw-app-eth/src/utils.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/src/utils'>;
}
