// flow-typed signature: 0a0109514498dad590607f7296d64eb4
// flow-typed version: <<STUB>>/@ledgerhq/hw-app-btc_v^4.57.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-app-btc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-app-btc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-app-btc/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-btc/flow-typed/npm/create-hash_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-btc/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-btc/src/Btc' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-btc/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-app-btc/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-btc/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-btc/flow-typed/npm/create-hash_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-btc/flow-typed/npm/create-hash_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-btc/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-btc/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-app-btc/src/Btc.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-btc/src/Btc'>;
}
declare module '@ledgerhq/hw-app-btc/src/utils.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-btc/src/utils'>;
}
