// flow-typed signature: 577daf8996b3b6d45c6d6daf7f2db08d
// flow-typed version: <<STUB>>/@ledgerhq/hw-app-xrp_v^4.57.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-app-xrp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-app-xrp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-app-xrp/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-xrp/flow-typed/npm/bip32-path_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-xrp/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-xrp/src/Xrp' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-app-xrp/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-xrp/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-xrp/flow-typed/npm/bip32-path_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-xrp/flow-typed/npm/bip32-path_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-xrp/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-xrp/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-app-xrp/src/Xrp.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-xrp/src/Xrp'>;
}
