// flow-typed signature: bf3abc75293a050142a7d00693cbe8c2
// flow-typed version: <<STUB>>/@ledgerhq/hw-transport-webusb_v^4.57.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-transport-webusb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-transport-webusb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/devices_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/errors_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/logs_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-webusb/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-webusb/flow/webusb' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-webusb/src/TransportWebUSB' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-webusb/src/webusb' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/devices_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/devices_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/errors_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/errors_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/logs_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-webusb/flow-typed/npm/@ledgerhq/logs_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-webusb/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-webusb/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-transport-webusb/flow/webusb.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-webusb/flow/webusb'>;
}
declare module '@ledgerhq/hw-transport-webusb/src/TransportWebUSB.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-webusb/src/TransportWebUSB'>;
}
declare module '@ledgerhq/hw-transport-webusb/src/webusb.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-webusb/src/webusb'>;
}
