// flow-typed signature: d541c4907805fa0b5c790f2a5c307cc4
// flow-typed version: <<STUB>>/@ledgerhq/hw-transport-node-hid_v^4.57.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-transport-node-hid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-transport-node-hid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/devices_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/errors_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/logs_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/node-hid_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/usb_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-node-hid/src/getDevices' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-node-hid/src/listenDevices' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-node-hid/src/TransportNodeHid' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/devices_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/devices_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/errors_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/errors_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/logs_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/flow-typed/npm/@ledgerhq/logs_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/flow-typed/npm/lodash_v4.x.x'>;
}
declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/node-hid_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/flow-typed/npm/node-hid_v0.x.x'>;
}
declare module '@ledgerhq/hw-transport-node-hid/flow-typed/npm/usb_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/flow-typed/npm/usb_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-node-hid/src/getDevices.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/src/getDevices'>;
}
declare module '@ledgerhq/hw-transport-node-hid/src/listenDevices.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/src/listenDevices'>;
}
declare module '@ledgerhq/hw-transport-node-hid/src/TransportNodeHid.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-node-hid/src/TransportNodeHid'>;
}
