// flow-typed signature: a01c3ffc559184f247c4ad0fe8e9ed88
// flow-typed version: <<STUB>>/@ledgerhq/errors_v^4.56.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/errors/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/errors/src/helpers' {
  declare module.exports: any;
}

declare module '@ledgerhq/errors/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/errors/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/errors/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/errors/src/helpers.js' {
  declare module.exports: $Exports<'@ledgerhq/errors/src/helpers'>;
}
declare module '@ledgerhq/errors/src/index.js' {
  declare module.exports: $Exports<'@ledgerhq/errors/src/index'>;
}
