// flow-typed signature: dd5e94188fbc7f62a31053cc914b4980
// flow-typed version: <<STUB>>/usb_v^1.5.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'usb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'usb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'usb/usb' {
  declare module.exports: any;
}

// Filename aliases
declare module 'usb/usb.js' {
  declare module.exports: $Exports<'usb/usb'>;
}
