// flow-typed signature: 6d38ac5002102a697470e4682d37c01e
// flow-typed version: <<STUB>>/@ledgerhq/hw-transport_v^4.57.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-transport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-transport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-transport/flow-typed/npm/@ledgerhq/devices_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport/flow-typed/npm/@ledgerhq/errors_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport/flow-typed/npm/@ledgerhq/logs_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport/flow-typed/npm/events_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport/src/Transport' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-transport/flow-typed/npm/@ledgerhq/devices_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/flow-typed/npm/@ledgerhq/devices_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport/flow-typed/npm/@ledgerhq/errors_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/flow-typed/npm/@ledgerhq/errors_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport/flow-typed/npm/@ledgerhq/logs_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/flow-typed/npm/@ledgerhq/logs_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport/flow-typed/npm/events_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/flow-typed/npm/events_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-transport/src/Transport.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/src/Transport'>;
}
