// flow-typed signature: 8130d9a7929cb0f834a25a8a029867be
// flow-typed version: <<STUB>>/@ledgerhq/logs_v^4.56.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/logs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/logs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/logs/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/logs/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/logs/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/logs/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/logs/src/index.js' {
  declare module.exports: $Exports<'@ledgerhq/logs/src/index'>;
}
