// flow-typed signature: 11aeb3626ce5a8c7744cf652ebb77e2c
// flow-typed version: <<STUB>>/ethereumjs-tx_v^1.3.7/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethereumjs-tx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethereumjs-tx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethereumjs-tx/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'ethereumjs-tx/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'ethereumjs-tx/es5/index' {
  declare module.exports: any;
}

declare module 'ethereumjs-tx/examples/transactions' {
  declare module.exports: any;
}

declare module 'ethereumjs-tx/fake' {
  declare module.exports: any;
}

declare module 'ethereumjs-tx/karma.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethereumjs-tx/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'ethereumjs-tx/coverage/lcov-report/prettify'>;
}
declare module 'ethereumjs-tx/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'ethereumjs-tx/coverage/lcov-report/sorter'>;
}
declare module 'ethereumjs-tx/es5/index.js' {
  declare module.exports: $Exports<'ethereumjs-tx/es5/index'>;
}
declare module 'ethereumjs-tx/examples/transactions.js' {
  declare module.exports: $Exports<'ethereumjs-tx/examples/transactions'>;
}
declare module 'ethereumjs-tx/fake.js' {
  declare module.exports: $Exports<'ethereumjs-tx/fake'>;
}
declare module 'ethereumjs-tx/index' {
  declare module.exports: $Exports<'ethereumjs-tx'>;
}
declare module 'ethereumjs-tx/index.js' {
  declare module.exports: $Exports<'ethereumjs-tx'>;
}
declare module 'ethereumjs-tx/karma.conf.js' {
  declare module.exports: $Exports<'ethereumjs-tx/karma.conf'>;
}
