// flow-typed signature: 97afb20670049c06ea81d1a743d9aaee
// flow-typed version: <<STUB>>/strip-hex-prefix_v^1.0.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strip-hex-prefix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strip-hex-prefix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'strip-hex-prefix/src/index' {
  declare module.exports: any;
}

declare module 'strip-hex-prefix/src/tests/test.index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'strip-hex-prefix/src/index.js' {
  declare module.exports: $Exports<'strip-hex-prefix/src/index'>;
}
declare module 'strip-hex-prefix/src/tests/test.index.js' {
  declare module.exports: $Exports<'strip-hex-prefix/src/tests/test.index'>;
}
