// flow-typed signature: 91a7eb62e0c9c04bc3e63bdb46a69259
// flow-typed version: <<STUB>>/events_v^3.0.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'events' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'events/events' {
  declare module.exports: any;
}

declare module 'events/tests/add-listeners' {
  declare module.exports: any;
}

declare module 'events/tests/check-listener-leaks' {
  declare module.exports: any;
}

declare module 'events/tests/common' {
  declare module.exports: any;
}

declare module 'events/tests/errors' {
  declare module.exports: any;
}

declare module 'events/tests/events-list' {
  declare module.exports: any;
}

declare module 'events/tests/index' {
  declare module.exports: any;
}

declare module 'events/tests/legacy-compat' {
  declare module.exports: any;
}

declare module 'events/tests/listener-count' {
  declare module.exports: any;
}

declare module 'events/tests/listeners-side-effects' {
  declare module.exports: any;
}

declare module 'events/tests/listeners' {
  declare module.exports: any;
}

declare module 'events/tests/max-listeners' {
  declare module.exports: any;
}

declare module 'events/tests/method-names' {
  declare module.exports: any;
}

declare module 'events/tests/modify-in-emit' {
  declare module.exports: any;
}

declare module 'events/tests/num-args' {
  declare module.exports: any;
}

declare module 'events/tests/once' {
  declare module.exports: any;
}

declare module 'events/tests/prepend' {
  declare module.exports: any;
}

declare module 'events/tests/remove-all-listeners' {
  declare module.exports: any;
}

declare module 'events/tests/remove-listeners' {
  declare module.exports: any;
}

declare module 'events/tests/set-max-listeners-side-effects' {
  declare module.exports: any;
}

declare module 'events/tests/special-event-names' {
  declare module.exports: any;
}

declare module 'events/tests/subclass' {
  declare module.exports: any;
}

declare module 'events/tests/symbols' {
  declare module.exports: any;
}

// Filename aliases
declare module 'events/events.js' {
  declare module.exports: $Exports<'events/events'>;
}
declare module 'events/tests/add-listeners.js' {
  declare module.exports: $Exports<'events/tests/add-listeners'>;
}
declare module 'events/tests/check-listener-leaks.js' {
  declare module.exports: $Exports<'events/tests/check-listener-leaks'>;
}
declare module 'events/tests/common.js' {
  declare module.exports: $Exports<'events/tests/common'>;
}
declare module 'events/tests/errors.js' {
  declare module.exports: $Exports<'events/tests/errors'>;
}
declare module 'events/tests/events-list.js' {
  declare module.exports: $Exports<'events/tests/events-list'>;
}
declare module 'events/tests/index.js' {
  declare module.exports: $Exports<'events/tests/index'>;
}
declare module 'events/tests/legacy-compat.js' {
  declare module.exports: $Exports<'events/tests/legacy-compat'>;
}
declare module 'events/tests/listener-count.js' {
  declare module.exports: $Exports<'events/tests/listener-count'>;
}
declare module 'events/tests/listeners-side-effects.js' {
  declare module.exports: $Exports<'events/tests/listeners-side-effects'>;
}
declare module 'events/tests/listeners.js' {
  declare module.exports: $Exports<'events/tests/listeners'>;
}
declare module 'events/tests/max-listeners.js' {
  declare module.exports: $Exports<'events/tests/max-listeners'>;
}
declare module 'events/tests/method-names.js' {
  declare module.exports: $Exports<'events/tests/method-names'>;
}
declare module 'events/tests/modify-in-emit.js' {
  declare module.exports: $Exports<'events/tests/modify-in-emit'>;
}
declare module 'events/tests/num-args.js' {
  declare module.exports: $Exports<'events/tests/num-args'>;
}
declare module 'events/tests/once.js' {
  declare module.exports: $Exports<'events/tests/once'>;
}
declare module 'events/tests/prepend.js' {
  declare module.exports: $Exports<'events/tests/prepend'>;
}
declare module 'events/tests/remove-all-listeners.js' {
  declare module.exports: $Exports<'events/tests/remove-all-listeners'>;
}
declare module 'events/tests/remove-listeners.js' {
  declare module.exports: $Exports<'events/tests/remove-listeners'>;
}
declare module 'events/tests/set-max-listeners-side-effects.js' {
  declare module.exports: $Exports<'events/tests/set-max-listeners-side-effects'>;
}
declare module 'events/tests/special-event-names.js' {
  declare module.exports: $Exports<'events/tests/special-event-names'>;
}
declare module 'events/tests/subclass.js' {
  declare module.exports: $Exports<'events/tests/subclass'>;
}
declare module 'events/tests/symbols.js' {
  declare module.exports: $Exports<'events/tests/symbols'>;
}
