// flow-typed signature: 02f3e95de88e3556ca1367cbbae40b70
// flow-typed version: <<STUB>>/@ledgerhq/hw-transport-mocker_v^4.57.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-transport-mocker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-transport-mocker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-transport-mocker/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-mocker/flow-typed/npm/@ledgerhq/logs_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-mocker/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-mocker/src/createTransportRecorder' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-mocker/src/createTransportReplayer' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-mocker/src/index' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-mocker/src/RecordStore' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-transport-mocker/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-mocker/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-mocker/flow-typed/npm/@ledgerhq/logs_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-mocker/flow-typed/npm/@ledgerhq/logs_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-mocker/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-mocker/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-transport-mocker/src/createTransportRecorder.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-mocker/src/createTransportRecorder'>;
}
declare module '@ledgerhq/hw-transport-mocker/src/createTransportReplayer.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-mocker/src/createTransportReplayer'>;
}
declare module '@ledgerhq/hw-transport-mocker/src/index.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-mocker/src/index'>;
}
declare module '@ledgerhq/hw-transport-mocker/src/RecordStore.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-mocker/src/RecordStore'>;
}
