// flow-typed signature: 165ce2995b6234b45f394f48cc975384
// flow-typed version: <<STUB>>/@ledgerhq/devices_v^4.57.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/devices'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/devices' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/devices/flow-typed/npm/@ledgerhq/errors_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/devices/flow-typed/npm/@ledgerhq/logs_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/devices/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/devices/flow-typed/npm/rxjs_v6.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/devices/src/ble/receiveAPDU' {
  declare module.exports: any;
}

declare module '@ledgerhq/devices/src/ble/sendAPDU' {
  declare module.exports: any;
}

declare module '@ledgerhq/devices/src/hid-framing' {
  declare module.exports: any;
}

declare module '@ledgerhq/devices/src/index' {
  declare module.exports: any;
}

declare module '@ledgerhq/devices/src/scrambling' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/devices/flow-typed/npm/@ledgerhq/errors_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/devices/flow-typed/npm/@ledgerhq/errors_vx.x.x'>;
}
declare module '@ledgerhq/devices/flow-typed/npm/@ledgerhq/logs_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/devices/flow-typed/npm/@ledgerhq/logs_vx.x.x'>;
}
declare module '@ledgerhq/devices/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/devices/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/devices/flow-typed/npm/rxjs_v6.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/devices/flow-typed/npm/rxjs_v6.x.x'>;
}
declare module '@ledgerhq/devices/src/ble/receiveAPDU.js' {
  declare module.exports: $Exports<'@ledgerhq/devices/src/ble/receiveAPDU'>;
}
declare module '@ledgerhq/devices/src/ble/sendAPDU.js' {
  declare module.exports: $Exports<'@ledgerhq/devices/src/ble/sendAPDU'>;
}
declare module '@ledgerhq/devices/src/hid-framing.js' {
  declare module.exports: $Exports<'@ledgerhq/devices/src/hid-framing'>;
}
declare module '@ledgerhq/devices/src/index.js' {
  declare module.exports: $Exports<'@ledgerhq/devices/src/index'>;
}
declare module '@ledgerhq/devices/src/scrambling.js' {
  declare module.exports: $Exports<'@ledgerhq/devices/src/scrambling'>;
}
