// flow-typed signature: f0da79e6cb87c46be72f935bd8dec327
// flow-typed version: <<STUB>>/create-hash_v^1.1.3/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'create-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'create-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'create-hash/browser' {
  declare module.exports: any;
}

declare module 'create-hash/md5' {
  declare module.exports: any;
}

declare module 'create-hash/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'create-hash/browser.js' {
  declare module.exports: $Exports<'create-hash/browser'>;
}
declare module 'create-hash/index' {
  declare module.exports: $Exports<'create-hash'>;
}
declare module 'create-hash/index.js' {
  declare module.exports: $Exports<'create-hash'>;
}
declare module 'create-hash/md5.js' {
  declare module.exports: $Exports<'create-hash/md5'>;
}
declare module 'create-hash/test.js' {
  declare module.exports: $Exports<'create-hash/test'>;
}
